[phases.setup]
nixPkgs = ["php84", "php84Extensions.pdo", "php84Extensions.mbstring", "php84Extensions.openssl", "php84Extensions.tokenizer", "php84Extensions.xml", "php84Extensions.curl", "php84Extensions.fileinfo", "php84Extensions.sqlite3", "php84Extensions.pdo_sqlite"]
